apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
    - host: http://34.76.75.227:8000/
      http:
        paths:
        - backend:
            serviceName: "test-server-service"
            servicePort: 8000
    - host: http://34.78.130.160:8000/
      http:
        paths:
        - backend:
            serviceName: "test-service2"
            servicePort: 8000