apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
      - http:
          paths:
          - backend:
              serviceName: "test-server-service"
              servicePort: 8000
            path: /get
            pathType: Prefix
      - http:
          paths:
          - backend:
              serviceName: "test-service2"
              servicePort: 8000
            path: /get2
            pathType: Prefix