apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
      - http:
          paths: /get
          - backend:
              serviceName: "test-server-service"
              servicePort: 8000
      - http:
          paths: /get2
          - backend:
              serviceName: "test-service2"
              servicePort: 8000