apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
    - host: test123.com
      http:
        paths:
        - backend:
            serviceName: "test-server-service"
            servicePort: 8000
    - host: test123.com
      http:
        paths:
        - backend:
            serviceName: "test-service2"
            servicePort: 8000