apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
      - containerPort: 27017
  nodeSelector:
    kubernetes.io/hostname: gke-cluster-2-default-pool-865d4d8a-208q
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    name: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017