apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server2
  labels:
    app: test-server2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-server2
  template:
    metadata:
      labels:
        app: test-server2
    spec:
      containers:
      - name: test-server-2
        image: mpyszynski/k8s-gcp:latest
        env:
          - name: NUM
            value: "2"
      nodeSelector:
        kubernetes.io/hostname: gke-cluster-1-default-pool-c18ec09f-kkvt
---
apiVersion: v1
kind: Service
metadata:
  name: test-service2
spec:
  type: LoadBalancer
  selector:
    app: test-server2
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
